'use client';
import {useEffect,useState} from 'react';
import {supabase} from '../../lib/supabase';

const labels:any={family_members:'Famiglia',household_tasks:'Casa',expenses:'Finanze',vehicles:'Veicoli',documents:'Documenti',events:'Agenda',shopping_items:'Spesa',inventory:'Inventario',subscriptions:'Abbonamenti',notes:'Note'};
const columns:any={family_members:['name','relationship','birth_date','phone','email','notes'],household_tasks:['title','assigned_to','due_date','completed','recurring','notes'],expenses:['description','amount','expense_date','paid_by','recurring','notes'],vehicles:['name','plate','brand','model','year','insurance_expiry','inspection_expiry','notes'],documents:['title','document_type','expiry_date','document_url','notes'],events:['title','event_date','location','description'],shopping_items:['item','quantity','category','purchased','notes'],inventory:['name','location','quantity','purchase_date','warranty_expiry','value','notes'],subscriptions:['name','provider','amount','billing_cycle','next_payment','active','notes'],notes:['title','content']};
const icons:any={family_members:'👨‍👩‍👧‍👦',household_tasks:'🏠',expenses:'💶',vehicles:'🚗',documents:'📄',events:'📅',shopping_items:'🛒',inventory:'📦',subscriptions:'🔁',notes:'📝'};
const pretty:any={name:'Nome',relationship:'Rapporto',birth_date:'Data di nascita',phone:'Telefono',email:'Email',notes:'Note',title:'Titolo',assigned_to:'Assegnato a',due_date:'Scadenza',completed:'Completata',recurring:'Ricorrente',description:'Descrizione',amount:'Importo',expense_date:'Data spesa',paid_by:'Pagato da',plate:'Targa',brand:'Marca',model:'Modello',year:'Anno',insurance_expiry:'Scadenza assicurazione',inspection_expiry:'Scadenza revisione',document_type:'Tipo documento',expiry_date:'Data scadenza',document_url:'Link documento',event_date:'Data e ora',location:'Luogo',item:'Articolo',quantity:'Quantità',category:'Categoria',purchased:'Acquistato',purchase_date:'Data acquisto',warranty_expiry:'Fine garanzia',value:'Valore',provider:'Fornitore',billing_cycle:'Ciclo di pagamento',next_payment:'Prossimo pagamento',active:'Attivo',content:'Contenuto'};
const textareaFields=new Set(['notes','description','content','address']);
const booleanFields=new Set(['completed','recurring','purchased','active']);
const dateFields=new Set(['birth_date','due_date','expense_date','insurance_expiry','inspection_expiry','expiry_date','purchase_date','warranty_expiry','next_payment']);
const numberFields=new Set(['amount','year','quantity','value']);
const timestampFields=new Set(['event_date']);
function inputType(field:string){if(dateFields.has(field))return 'date';if(timestampFields.has(field))return 'datetime-local';if(numberFields.has(field))return 'number';return 'text'}
function initialValue(field:string){if(booleanFields.has(field))return false;return ''}
function toInputValue(field:string,value:any){if(value==null)return '';if(timestampFields.has(field)){const d=new Date(value);if(Number.isNaN(d.getTime()))return '';return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}return String(value)}
function fromInputValue(field:string,value:any){if(value===''&&(dateFields.has(field)||numberFields.has(field)))return null;if(timestampFields.has(field)&&value)return new Date(value).toISOString();if(numberFields.has(field)&&value!=='')return Number(value);return value}

export default function Area(){
 const [t,setT]=useState('');const [rows,setRows]=useState<any[]>([]);const [canEdit,setCanEdit]=useState(false);const [loading,setLoading]=useState(true);const [editing,setEditing]=useState<any|null>(null);const [saving,setSaving]=useState(false);const [form,setForm]=useState<Record<string,any>>({});const [error,setError]=useState('');
 useEffect(()=>{const p=new URLSearchParams(window.location.search);setT(p.get('table')||'')},[]);
 async function load(){if(!columns[t]){setLoading(false);return}setError('');const s=supabase();const {data,error}=await s.from(t).select('*').order('created_at',{ascending:false});if(error){setError(error.message);setRows([])}else setRows(data||[]);const {data:u}=await s.auth.getUser();if(u.user){const p=await s.from('family_profiles').select('role').eq('id',u.user.id).maybeSingle();setCanEdit(p.data?.role==='owner')}setLoading(false)}
 useEffect(()=>{if(t)load()},[t]);
 function openAdd(){const values:any={};columns[t].forEach((f:string)=>values[f]=initialValue(f));setError('');setEditing({mode:'add'});setForm(values)}
 function openEdit(row:any){const values:any={};columns[t].forEach((f:string)=>values[f]=toInputValue(f,row[f]));setError('');setEditing({mode:'edit',id:row.id});setForm(values)}
 function closeForm(){if(!saving)setEditing(null)}
 async function save(e:any){e.preventDefault();setSaving(true);setError('');const payload:any={};columns[t].forEach((f:string)=>{payload[f]=fromInputValue(f,form[f])});const s=supabase();const result=editing.mode==='add'?await s.from(t).insert(payload):await s.from(t).update(payload).eq('id',editing.id);if(result.error)setError(result.error.message);else{setEditing(null);await load()}setSaving(false)}
 async function del(id:string){if(!confirm('Eliminare questa voce?'))return;const {error}=await supabase().from(t).delete().eq('id',id);if(error)alert(error.message);else load()}
 if(loading)return <main className="wrap"><div className="loading">Caricamento…</div></main>;
 const label=labels[t]||t;
 if(!columns[t])return <main className="wrap"><div className="top"><div><a className="muted" href="../index.html">← Torna al menu</a><div className="brand">Sezione non trovata</div></div></div><div className="card empty"><div className="section-icon">🔎</div><h2>Questa sezione non esiste</h2><p className="muted">Torna al menu principale per scegliere una sezione valida.</p><a className="btn" href="../index.html">Torna al menu</a></div></main>;
 return <main className="wrap"><div className="top"><div><a className="muted" href="../index.html">← Torna al menu</a><div className="brand">{icons[t]} {label}</div></div>{canEdit&&<button className="btn" onClick={openAdd}>+ Aggiungi</button>}</div>
 <div className="card"><div className="muted" style={{marginBottom:12}}>{canEdit?'Sei il proprietario: puoi aggiungere, modificare ed eliminare i dati.':'Accesso in sola lettura.'}</div>
 {rows.length===0?<div className="empty"><div className="section-icon">{icons[t]}</div><h2>{error?'Impossibile caricare i dati':'Qui non c’è ancora nulla'}</h2><p className="muted">{error||'Aggiungi il primo elemento compilando i campi della categoria.'}</p>{canEdit&&<button className="btn" onClick={openAdd}>+ Aggiungi il primo elemento</button>}<div><a className="linkbtn" href="../index.html">← Torna al menu principale</a></div></div>:<div style={{overflowX:'auto'}}><table className="table"><thead><tr>{columns[t].map((c:string)=><th key={c}>{pretty[c]||c.replaceAll('_',' ')}</th>)}{canEdit&&<th>Azioni</th>}</tr></thead><tbody>{rows.map(r=><tr key={r.id}>{columns[t].map((c:string)=><td key={c}>{booleanFields.has(c)?(r[c]?'Sì':'No'):String(r[c]??'')}</td>)}{canEdit&&<td className="row-actions"><button className="btn secondary" onClick={()=>openEdit(r)}>Modifica</button><button className="btn secondary danger" onClick={()=>del(r.id)}>Elimina</button></td>}</tr>)}</tbody></table></div>}
 </div>
 {editing&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)closeForm()}}><div className="modal card"><div className="modal-head"><div><div className="eyebrow">{editing.mode==='add'?'NUOVO ELEMENTO':'MODIFICA ELEMENTO'}</div><h2>{editing.mode==='add'?`Aggiungi in ${label}`:`Modifica elemento`}</h2></div><button className="close" type="button" onClick={closeForm}>×</button></div><form onSubmit={save}><div className="form-grid">{columns[t].map((field:string)=>booleanFields.has(field)?<label className="check-field" key={field}><input type="checkbox" checked={!!form[field]} onChange={e=>setForm({...form,[field]:e.target.checked})}/><span>{pretty[field]||field}</span></label>:<label className="field" key={field}><span>{pretty[field]||field}</span>{textareaFields.has(field)?<textarea rows={4} value={form[field]??''} onChange={e=>setForm({...form,[field]:e.target.value})}/>:<input type={inputType(field)} value={form[field]??''} onChange={e=>setForm({...form,[field]:e.target.value})} required={field==='name'||field==='title'||field==='item'||(field==='description'&&t==='expenses')}/>}</label>)}</div>{error&&<div className="error">{error}</div>}<div className="modal-actions"><button className="btn secondary" type="button" onClick={closeForm}>Annulla</button><button className="btn" disabled={saving}>{saving?'Salvataggio…':'Salva'}</button></div></form></div></div>}
 </main>
}
